version: "3.9"
services:
  nginx:
    image: "nginx:alpine"
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8010:80"

  hermes:
    image: "wirkijowskidev/hermes"
    container_name: hermes
    environment:
      PORT: 4000
    expose:
      - 4000
    depends_on:
      - nginx
    extra_hosts:
      - "database:172.17.0.1"

  gateway_redis:
    image: "redis:alpine"
    container_name: gateway_redis
    expose:
      - 6379

  gateway:
    image: "wirkijowskidev/hermes-gateway"
    environment:
      PORT: 5000
    depends_on:
      - hermes
      - nginx
      - gateway_redis